package com.exam.me.ui.admin

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.exam.me.data.local.SessionManager
import com.exam.me.model.Movie
import com.exam.me.network.RetrofitInstance
import com.exam.me.repository.UserRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch

sealed class AddMovieResult {
    object Idle : AddMovieResult()
    object Loading : AddMovieResult()
    data class Success(val movie: Movie) : AddMovieResult()
    data class Error(val message: String) : AddMovieResult()
}

data class AddMovieFormState(
    val titulo: String = "",
    val director: String = "",
    val anio: String = "",
    val duracion: String = "",
    val genero: String = "",
    val tituloError: String? = null,
    val directorError: String? = null,
    val anioError: String? = null,
    val duracionError: String? = null,
    val generoError: String? = null,
    val isFormValid: Boolean = false
)

class AddMovieViewModel(application: Application) : AndroidViewModel(application) {

    private val userRepository = UserRepository(RetrofitInstance.api, SessionManager(getApplication()))

    private val _formState = MutableStateFlow(AddMovieFormState())
    val formState: StateFlow<AddMovieFormState> = _formState.asStateFlow()

    private val _addMovieResult = MutableStateFlow<AddMovieResult>(AddMovieResult.Idle)
    val addMovieResult: StateFlow<AddMovieResult> = _addMovieResult.asStateFlow()

    fun onFormChange(titulo: String, director: String, anio: String, duracion: String, genero: String) {
        _formState.update { it.copy(titulo = titulo, director = director, anio = anio, duracion = duracion, genero = genero) }
        validateForm()
    }

    private fun validateForm() {
        val state = _formState.value
        val anioInt = state.anio.toIntOrNull()
        val duracionInt = state.duracion.toIntOrNull()

        val tituloError = if (state.titulo.isBlank()) "Title is required" else null
        val directorError = if (state.director.isBlank()) "Director is required" else null
        val generoError = if (state.genero.isBlank()) "Genre is required" else null
        val anioError = if (anioInt == null || anioInt <= 1800) "Invalid year" else null
        val duracionError = if (duracionInt == null || duracionInt <= 0) "Invalid duration" else null

        _formState.update {
            it.copy(
                tituloError = tituloError,
                directorError = directorError,
                anioError = anioError,
                duracionError = duracionError,
                generoError = generoError,
                isFormValid = tituloError == null && directorError == null && anioError == null && duracionError == null && generoError == null
            )
        }
    }

    fun createMovie() {
        validateForm()
        if (!_formState.value.isFormValid) return

        viewModelScope.launch {
            _addMovieResult.value = AddMovieResult.Loading
            try {
                val state = _formState.value
                val movie = Movie(
                    id = "", // ID is generated by backend
                    titulo = state.titulo,
                    director = state.director,
                    anio = state.anio.toInt(),
                    duracion = state.duracion.toInt(),
                    genero = state.genero,
                    imagen = null,
                    imagenThumbnail = null
                )
                val result = userRepository.createMovie(movie)
                _addMovieResult.value = AddMovieResult.Success(result)
            } catch (e: Exception) {
                _addMovieResult.value = AddMovieResult.Error(e.message ?: "An unexpected error occurred")
            }
        }
    }
}